## Part 1

In [79]:
import numpy as np
import collections

In [173]:
with open('input.csv') as f:
    lines = f.readlines()
    
drawn_numbers = list(map(int,lines[0].split()[0].split(',')))
bingo_data = lines[2:]

In [220]:
bingo_sheets = np.loadtxt(bingo_data)
bingo_sheets = np.split(bingo_sheets.astype(int), len(bingo_sheets)/5)

bingo_sheets_master = np.copy(bingo_sheets)

winner_found = False

for drawn_number in drawn_numbers:
    
    # print('------------------')
    # print(f'Drawn Number: {drawn_number} \n')
    
    # check if a winner was found
    if winner_found == True:
        break
    
    for index, bingo_sheet in enumerate(bingo_sheets):
        
        # print(f'Checking Sheet: {index} \n')
        
        # cross out any matching numbers
        match = np.where(bingo_sheet == drawn_number)
        if match[0].size == 0: # no match found
            continue
        else:
            row = match[0][0] # row
            column = match[1][0] # column
            bingo_sheet[row][column] = -1
            
            # check if any columns or rows have been fully crossed out
            for line in range(5):
                # check each column
                if (bingo_sheet[:,line] > 0).sum() == 0:
                    print(f'BINGO!! Sheet: {index} \n {bingo_sheet}')
                    winner, winning_number, winner_found = index, bingo_sheets_master[winner][match][0], True
                    
                # check each row
                if (bingo_sheet[line] > 0).sum() == 0:
                    print(f'BINGO!! Sheet: {index} \n {bingo_sheet}')
                    winner, winning_number, winner_found = index, bingo_sheets_master[winner][match][0], True
                
        # print(f'Sheet: {index} \n {bingo_sheet} \n')


BINGO!! Sheet: 85 
 [[55 15 85 39  4]
 [-1 -1 -1 -1 -1]
 [-1 47 61  9 66]
 [82 32 -1 -1 16]
 [50 96 14 60 35]]


In [215]:
def sum_leftovers(array):
    return array[array > 0].sum()

sumofrows = np.apply_along_axis(sum_leftovers, 1, bingo_sheets[winner])
sumofsheet = sum(sumofrows)    
sumofsheet

766

In [216]:
winning_number

95

In [223]:
sumofsheet * winning_number

72770

## Part 2

In [273]:
with open('input.csv') as f:
    lines = f.readlines()
    
drawn_numbers = list(map(int,lines[0].split()[0].split(',')))
bingo_data = lines[2:]

In [274]:
bingo_sheets = np.loadtxt(bingo_data)
bingo_sheets = np.split(bingo_sheets.astype(int), len(bingo_sheets)/5)
bingo_sheets_master = np.copy(bingo_sheets)

leader_board = []

for drawn_number in drawn_numbers:
    
    # print('------------------')
    # print(f'Drawn Number: {drawn_number} \n')
    
    for index, bingo_sheet in enumerate(bingo_sheets):
        
        # don't check any winner sheets
        if index in leader_board:
            # print(f'Sheet {index} is a winner! \n')
            continue
        
        # cross out any matching numbers
        match = np.where(bingo_sheet == drawn_number)
        if match[0].size == 0: # no match found
            continue
        else:
            row = match[0][0] # row
            column = match[1][0] # column
            bingo_sheet[row][column] = -1
            
            # check if any columns or rows have been fully crossed out
            for line in range(5):
                # check each column
                if (bingo_sheet[:,line] > 0).sum() == 0:
                    leader_board.append(index)
                    winning_number = bingo_sheets_master[index][match][0]
                    break
                    
                # check each row
                if (bingo_sheet[line] > 0).sum() == 0:
                    leader_board.append(index)
                    winning_number = bingo_sheets_master[index][match][0]
                    break
                
        # print(f'Sheet: {index} \n {bingo_sheet} \n')

print(leader_board)

[85, 35, 59, 22, 28, 0, 55, 97, 50, 51, 58, 94, 36, 52, 66, 9, 93, 96, 60, 14, 49, 63, 70, 86, 95, 34, 47, 99, 3, 15, 53, 64, 88, 23, 26, 30, 72, 73, 98, 76, 25, 89, 32, 79, 82, 8, 37, 77, 78, 80, 65, 92, 5, 44, 46, 54, 57, 29, 68, 12, 90, 17, 24, 39, 40, 45, 67, 1, 2, 48, 71, 87, 18, 62, 11, 16, 61, 91, 41, 21, 43, 6, 13, 33, 56, 10, 84, 31, 38, 83, 27, 42, 81, 74, 19, 4, 7, 20, 69, 75]


In [275]:
winning_number

47

In [276]:
sumofrows = np.apply_along_axis(sum_leftovers, 1, bingo_sheets[leader_board[-1]])
sumofsheet = sum(sumofrows)    
sumofsheet

296

In [277]:
sumofsheet * winning_number

13912

## Object Oriented Design

In [ ]:
class Sheet:
    def __init__(self, sheet):
        self.sheet = sheet
    
    def finished(self):
        pass
    
    def mark(self, number):
        indices = list(zip(*np.where(self.sheet == number)))
        for row, column in indices:
            self.sheet[row, column] = -1
        return len(indices) > 0
        
    def __repr__(self):
        return repr(self.sheet)
         
sheets = [Sheet(sheet) for sheet in bingo_sheets]
sheets[0].mark(13)
sheets[0]

In [ ]:
class Board:
    
    board_nums = [][]
    board_marked = [][]
    
    def contains(num):
        pass
    
    def mark():
    
    def finished():
        # check horizontal & vertical lines
        arr.some(e => e.all(x = xx) and arr.all(e.some(x = xx)