## Part 1

In [170]:
import numpy as np
import collections

In [171]:
with open('test.csv') as f:
    lines = f.readlines()

In [208]:
drawn_numbers = list(map(int,lines[0].split()[0].split(',')))
bingo_data = lines[2:]

bingo_sheets = np.loadtxt(bingo_data)
bingo_sheets = np.split(bingo_sheets.astype(int), len(bingo_sheets)/5)
bingo_sheets

[array([[22, 13, 17, 11,  0],
        [ 8,  2, 23,  4, 24],
        [21,  9, 14, 16,  7],
        [ 6, 10,  3, 18,  5],
        [ 1, 12, 20, 15, 19]]),
 array([[ 3, 15,  0,  2, 22],
        [ 9, 18, 13, 17,  5],
        [19,  8,  7, 25, 23],
        [20, 11, 10, 24,  4],
        [14, 21, 16, 12,  6]]),
 array([[14, 21, 17, 24,  4],
        [10, 16, 15,  9, 19],
        [18,  8, 23, 26, 20],
        [22, 11, 13,  6,  5],
        [ 2,  0, 12,  3,  7]])]

In [173]:
drawn_numbers[0]

7

In [174]:
match = np.where(bingo_sheets[0] == drawn_numbers[0])
row = match[0][0] # row
column = match[1][0] # column
print(row, column)

2 4


In [222]:
class Sheet:
    def __init__(self, sheet):
        self.sheet = sheet
    
    def finished(self):
        pass
    
    def mark(self, number):
        indices = list(zip(*np.where(self.sheet == number)))
        for row, column in indices:
            self.sheet[row, column] = -1
        return len(indices) > 0
        
    def __repr__(self):
        return repr(self.sheet)
         
sheets = [Sheet(sheet) for sheet in bingo_sheets]
sheets[0].mark(13)
sheets[0]

array([[-1, -1, 17, 11,  0],
       [ 8,  2, 23,  4, 24],
       [21,  9, 14, 16,  7],
       [ 6, 10,  3, 18,  5],
       [ 1, 12, 20, 15, 19]])

In [180]:
for number in drawn_numbers:
    try:
        for sheet in sheets:
            if sheet.mark(number):
                print(sheet)
    except:
        pass

[[22 13 17 11  0]
 [ 8  2 23 -1 24]
 [21  9 14 16 -1]
 [ 6 10  3 18  5]
 [ 1 12 20 15 19]]
[[ 3 15  0  2 22]
 [ 9 18 13 17  5]
 [19  8  7 25 23]
 [20 11 10 24 -1]
 [14 21 16 12  6]]
[[14 21 17 24 -1]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]
[[22 13 17 11  0]
 [ 8  2 23 -1 24]
 [21 -1 14 16 -1]
 [ 6 10  3 18  5]
 [ 1 12 20 15 19]]
[[ 3 15  0  2 22]
 [-1 18 13 17  5]
 [19  8  7 25 23]
 [20 11 10 24 -1]
 [14 21 16 12  6]]
[[14 21 17 24 -1]
 [10 16 15 -1 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]
[[22 13 17 11  0]
 [ 8  2 23 -1 24]
 [21 -1 14 16 -1]
 [ 6 10  3 18 -1]
 [ 1 12 20 15 19]]
[[ 3 15  0  2 22]
 [-1 18 13 17 -1]
 [19  8  7 25 23]
 [20 11 10 24 -1]
 [14 21 16 12  6]]
[[14 21 17 24 -1]
 [10 16 15 -1 19]
 [18  8 23 26 20]
 [22 11 13  6 -1]
 [ 2  0 12  3  7]]
[[22 13 17 -1  0]
 [ 8  2 23 -1 24]
 [21 -1 14 16 -1]
 [ 6 10  3 18 -1]
 [ 1 12 20 15 19]]
[[ 3 15  0  2 22]
 [-1 18 13 17 -1]
 [19  8  7 25 23]
 [20 -1 10 24 -1]
 [14 21 16 12  6]]

In [178]:
for number in drawn_numbers:
    for sheet in bingo_sheets:
        match = np.where(sheet == number)
        print(match)

(array([], dtype=int64), array([], dtype=int64))
(array([2]), array([2]))
(array([4]), array([4]))
(array([1]), array([3]))
(array([3]), array([4]))
(array([0]), array([4]))
(array([2]), array([1]))
(array([1]), array([0]))
(array([1]), array([3]))
(array([3]), array([4]))
(array([1]), array([4]))
(array([3]), array([4]))
(array([0]), array([3]))
(array([3]), array([1]))
(array([3]), array([1]))
(array([0]), array([2]))
(array([1]), array([3]))
(array([0]), array([2]))
(array([1]), array([2]))
(array([2]), array([4]))
(array([2]), array([2]))
(array([1]), array([1]))
(array([0]), array([3]))
(array([4]), array([0]))
(array([0]), array([4]))
(array([0]), array([2]))
(array([4]), array([1]))
(array([2]), array([2]))
(array([4]), array([0]))
(array([0]), array([0]))
(array([2]), array([0]))
(array([4]), array([1]))
(array([0]), array([1]))
(array([1]), array([4]))
(array([3]), array([3]))
(array([0]), array([3]))
(array([3]), array([1]))
(array([3]), array([2]))
(array([1]), array([0]))
(

In [175]:
bingo_sheets[0][row, column] = -1
bingo_sheets

[array([[22, 13, 17, 11,  0],
        [ 8,  2, 23,  4, 24],
        [21,  9, 14, 16, -1],
        [ 6, 10,  3, 18,  5],
        [ 1, 12, 20, 15, 19]]),
 array([[ 3, 15,  0,  2, 22],
        [ 9, 18, 13, 17,  5],
        [19,  8,  7, 25, 23],
        [20, 11, 10, 24,  4],
        [14, 21, 16, 12,  6]]),
 array([[14, 21, 17, 24,  4],
        [10, 16, 15,  9, 19],
        [18,  8, 23, 26, 20],
        [22, 11, 13,  6,  5],
        [ 2,  0, 12,  3,  7]])]

In [123]:
bingo_sheets[0].astype(int)

array([[22, 13, 17, 11,  0],
       [ 8,  2, 23,  4, 24],
       [21,  9, 14, 16,  7],
       [ 6, 10,  3, 18,  5],
       [ 1, 12, 20, 15, 19]])

In [118]:
(bingo_sheets[0] > 15).any(0) #column

array([ True, False,  True,  True,  True])

In [129]:
collections.Counter(bingo_sheets[0][0])

Counter({22.0: 1, 13.0: 1, 17.0: 1, 11.0: 1, 0.0: 1})

In [120]:
(bingo_sheets[0] > 20).any(1) #row

array([ True,  True,  True, False, False])

In [93]:
bingo_sheets[0][0]

array(['22', '13', '17', '11', '0'], dtype='<U2')

In [ ]:
class Board:
    
    bord_nums = [][]
    board_marked = [][]
    
    def contains(num):
        pass
    
    def mark():
    
    def finished():
        # check horizontal & vertical lines
        arr.some(e => e.all(x = xx) and arr.all(e.some(x = xx)